### ISSUE TITLE
Networking isn't compatible with esp-idf 5.x

### ISSUE THREAD

**Issue by tomvanbraeckel** [ducalex/retro-go#126]
When building with ESP-IDF version: v5.2.2, I'm getting the warning "Networking isn't compatible with esp-idf 5.x" and indeed, this isn't compiled in.

What would it take to get the networking to work again with ESP-IDF v5.x?

As more and more projects are moving to that latest version, including the MicroPython that the Fri3D Camp 2024 badge uses, it would be great to get that working again :-)

**Comment by ducalex** [comment]
If I recall correctly the main changes were in the event handling as well as some lwip stuff (like tcpip_adapter_*).

It shouldn't be that hard to fix, I just never put in the time. 

Maybe we could also look into using esp-idf's SNTP support instead of my home made time sync function, now that I no longer need to support esp-idf older than 4.3.
