### ISSUE TITLE
Compilation failure due to sntp_stop()

### ISSUE THREAD

**Issue by tomvanbraeckel** [ducalex/retro-go#141]
While building with ESP-IDF v5.2.2, I'm getting this error:

```
/retro-go-fri3d/components/retro-go/rg_network.c: In function 'network_event_handler':
/retro-go-fri3d/components/retro-go/rg_network.c:85:13: error: implicit declaration of function 'sntp_stop' [-Werror=implicit-function-declaration]
   85 |             sntp_stop();
      |             ^~~~~~~~~

```

Also, deprecation warnings:
```
warning: 'sntp_init' is deprecated: use esp_sntp_init() instead [-Wdeprecated-declarations]
```

This diff fixes it:

```
diff --git a/components/retro-go/rg_network.c b/components/retro-go/rg_network.c
index db1beec3..fd1ba188 100644
--- a/components/retro-go/rg_network.c
+++ b/components/retro-go/rg_network.c
@@ -82,7 +82,7 @@ static void network_event_handler(void *arg, esp_event_base_t event_base, int32_
             RG_LOGI("Connected! IP: %s, RSSI: %d", network.ip_addr, network.rssi);
             rg_system_event(RG_EVENT_NETWORK_CONNECTED, NULL);
 
-            sntp_stop();
+            esp_sntp_stop();
             sntp_init();
         }
         else if (event_id == IP_EVENT_AP_STAIPASSIGNED)
```

I find it a bit strange that this one function needs the esp_ prefix while the others is fine. I would send a pull request to fix it but haven't tested on ESP < 5.x so thought I would just report it instead.

**Comment by ducalex** [comment]
Thanks for catching this, I only tested 4.3/5.0. They change the SNTP API in every esp-idf version it's very annoying. That's why I made my own initially... In esp-idf 5.1+ they seem to have stubbed sntp_init but not sntp_stop for whatever reason.

I've added a wokraround so that it can work for now, but I'll look into what's the most reasonable long-term solution later.
